### ISSUE TITLE
Cookiebot

### ISSUE THREAD

**Issue by lplusl** [heimrichhannot/contao-video-bundle#1]
In Kombination mit der Erweiterung "cookiebot" scheint es zu einem Fehler zu kommen.
Das Hinweis-Popup vom video-bundle öffnet sich bei Klick auf das Vorschaubild erst nach einem Refresh der Seite.

**Comment by koertho** [comment]
@lplusl Hi, so wie ich das sehe, blockiert dieser cookiebot-skript die Ausführung unseres Skriptes auf der Seite. Hier müsstet ihr mal schauen, ob der Skript gar nicht geladen wird oder ob die Ausführung erst zu einem bestimmten Zeitpunkt unterbrochen wird, bspw. beim Zugriff auf localStorage. Eventuell könnte man dann da einen Event einbauen. Alternativ ist es vielleicht auch möglich, von Cookiebot eine Ausnahme erstellen zu lassen. Aber leider können wir da nicht helfen, da der Fehler nichts mit unserer Erweiterung zu tun hat und wir cookiebot nicht einsetzen.
Eventuell hilft euch die Entwickler-Dokumentation weiter: https://www.cookiebot.com/de/developer/
Falls ihr irgendwo noch einen Event braucht, macht einfach einen Pull-Request oder erstellt ein Feature-Request-Issue.
