### ISSUE TITLE
News: Add video-file is missing source field

### ISSUE THREAD

**Issue by Webstylerin** [heimrichhannot/contao-video-bundle#12]
**Context**
Contao version: 4.13.5
Bundle version: 1.0.3
PHP version: 7.4.30

**Description**
I enabled news support via config.yml and the video settings are shown in my news element. When i choose file as video provider there is no field to select my video file.
![Bildschirmfoto 2022-06-29 um 10 35 15](https://user-images.githubusercontent.com/3033160/176391467-3853ac3a-8a71-45c6-9f98-07ed547dde62.png)

**Comment by Webstylerin** [comment]
Hi, thank you, looks like it's working now. :)

**Comment by koertho** [comment]
Great to hear that! Thanks for reporting!
