### ISSUE TITLE
Missing "Add Video" for Newselement

### ISSUE THREAD

**Issue by Misco** [heimrichhannot/contao-video-bundle#13]
Installed on C4.13
No Errors but no Fields in the Newselement =(

**Comment by koertho** [comment]
Do you mean the normal news or content element of the extension news element?

**Comment by Misco** [comment]
Where you write the teaser, there should be a checkmark or?
Or should I use the other news video extension? That looked a bit bugy with
double fields.
Thanks

Thomas ***@***.***> schrieb am Mi., 21. Dez. 2022, 07:34:

**Comment by koertho** [comment]
Sorry, I don't know what you mean. The newselement extension is not supported. If you want to use it from the normal contao news, you need to activate it as described in the readme.

**Comment by Misco** [comment]
thank you, i missed that part
