### ISSUE TITLE
Issue after updating Contao 4.13

### ISSUE THREAD

**Issue by lplusl** [heimrichhannot/contao-video-bundle#14]
Contao version: 4.13.15
Bundle version: 1.1.1
PHP version: 8.1.13

Nach dem Update auf Contao 4.13 läuft das Bundle nicht mehr richtig. Das Video startet automatisch ohne das erforderliche OK über das Dialogfenster. 
Zudem aufgefallen ist die Darstellung im Code:
![Bildschirmfoto 2023-01-13 um 16 59 45](https://user-images.githubusercontent.com/62538015/212650142-0fc4160f-decc-4df0-bcd6-ea7cda91b637.png)

Danke für kurzes Feedback und Lösungsvorschlag.

**Comment by koertho** [comment]
Should be fixed in 1.2.0
