### ISSUE TITLE
Urgent: Support needed for new Vimeo ID syntax

### ISSUE THREAD

**Issue by lplusl** [heimrichhannot/contao-video-bundle#17]
Dear People at HuH,

Vimeo has changed the IDs for "unlisted" videos (prior mode name: "hidden"). The ID now consists of longer string (example: 000000000/e0e7215c96).

Could you please kindly allow longer ID strings. This would be required urgently. Thank you!

**Comment by koertho** [comment]
Hi, we're currently very busy so I can't promise a soon fix. As workaround you could easily adjust the dca yourself. And if you provide your fix as PR, I think I find time to merge it.

**Comment by lplusl** [comment]
Thank you for the quick reply, we will have a look at that.

**Comment by zonky2** [comment]
@koertho Moin, der Parameter muss nun als GET-Parameter in die iFrame-URL mit rein als `h=123456789` - wenn man den Parameter mit `?` beim Vimeo-Key mit einträgt hat am am Ende zwei `?`in der URL und ist nicht mehr valide...

Ich habe erstmal einen kleinen, temporären Fix eingebaut, der das Splittet und als Parameter anhängt.

Mein Vorschlag wäre, ein weiteres Feld für optionale GET-Parameter - der String, wenn gefüllt, wird mit `& ` mit angehangen...

Was sagt ihr dazu? Ist jemand von Euch auf dem Camp in Regensburg?

**Comment by koertho** [comment]
@zonky2 Kannst du mir ein vorher/nachher Beispiel geben? Kann gerade nicht so richtig erschließen, was sicher außer der Länge der Video-ID geändert hat. 
Die URL wird hier generiert: https://github.com/heimrichhannot/contao-video-bundle/blob/10493a1ff3a7ea3cbfaec547f0d5fa975b032d65/src/Video/VimeoVideo.php#L77
Wenn die ID nun einfach als GET-Parameter angehangen werden muss, muss ja nur die Methode angepasst werden.

**Comment by zonky2** [comment]
also, was eingetragen wurde ist sowas wie `123456789?h=e0e7215c96` ... in der URL des iframes steht dann sowas wie `...123456789?h=e0e7215c96?dnt=1&autoplay=1` - mit den zwei `?` geht das natürlich nicht... aktuell splitte ich `123456789?h=e0e7215c96` und schleuse `h=e0e7215c96` mit ein....

Ich würde ein neues DCA-Feld machen wo `h=e0e7215c96&key=wasweissich&yek=hierundda` rein kann, was dann einfach mit `?` bzw. `&` an die bestehende URL drann kommt.... ggf. kommen bei YT ja auch mal weitere Parameter

**Comment by zonky2** [comment]
@koertho was sagst Du dazu?

**Comment by koertho** [comment]
Mhm, bin nicht so ein Fan von solchen Feldern, das ist nicht sehr benutzerfreundlich. Wenn der zusätzliche Query sowieso ein Vimeo-Standard ist, sollte es auch ein festes Feld sein.

**Comment by zonky2** [comment]
o.k. - habe nochmal in der API nachgesehen `h` steht für "hash parameter"

**Comment by koertho** [comment]
Fixed in #18
