### ISSUE TITLE
Link zum Vimeo Datenschutz

### ISSUE THREAD

**Issue by lplusl** [heimrichhannot/contao-video-bundle#2]
Kann man einen Link zum Datenschutz von Vimeo im Popup einbinden, bei dem der User nachsehen kann was genau mit seinen Daten passiert?

**Comment by koertho** [comment]
@lplusl Hi, es gibt zwei Möglichkeiten: 

1. Ein eigenes privacy-template anlegen (oder das default überschreiben) (https://github.com/heimrichhannot/contao-video-bundle/blob/master/src/Resources/views/privacy/videoprivacy_default.html.twig) 
1. Den Text für den Video-Provider anpassen: https://github.com/heimrichhannot/contao-video-bundle/blob/master/src/Resources/translations/messages.de.yml

Texte und sonstige Inhalte könenn auch noch über das BeforeRenderPlayerEvent angepasst werden, damit ließen sich solche anpassungen auch dynamisch machen.

**Comment by lplusl** [comment]
danke für die Rückmeldung! Ist das dann auch updatesicher? Wäre es möglich die Erweiterung um ein Eingabefeld im Inhaltselement zu erweitern, sodass man dort auch die Möglichkeit bekommt einen Link zur eigenen Datenschutzerklärung einzubinden? So wäre es um einiges leichter zu konfigurieren.

**Comment by koertho** [comment]
Richtig. In diesem Fall würde ich die DCA um eine Datenschutzseiten-Auswahl erweitern, im BeforeRenderPlayerEvent dieses auswerten und dann ensprechend im Template oder der Übersetzung ausgeben.

**Comment by koertho** [comment]
Ach so, um deine Frage zum Thema Updatesicherheit zu beantworten: Ja, genau dafür sind Events und Template-Überschreibung da ;) Natürlich mit der Einschränkung, dass wir uns an Semantic Versioning halten, also Schnittstellen-Änderungen in Major-Versionen kommen können (bei Vorabversionen schon in Minor-Versionen (und wir haben hier eine Version 0.1, also eine Vorabversion).).

**Comment by zonky2** [comment]
unter C4.4 wäre das `app/Resources/translations` für den Pfad der `messages.*.yml`

@koertho aktuell wird aber kein HTML-Code unterstützt, so dass man keinen Link eingeben kann bzw. dieser als kompletter Quelltext ausgegeben wird

**Comment by lplusl** [comment]
wie zonky schon geschrieben hat, wird html-code im popup nicht unterstützt. könntet ihr das bitte möglich machen? So ist es leider nicht optimal, wenn man links einsetzen will/muss.

<img width="547" alt="Bildschirmfoto 2020-06-15 um 08 34 13" src="https://user-images.githubusercontent.com/62538015/84625224-246aa700-aee3-11ea-9f2a-0a2c9f81bbd2.png">

**Comment by koertho** [comment]
Hallo, HTML wird sehr wohl unterstützt, wenn man im privacy-template den raw filter an die checkbox-variable anhängt (`<input type="checkbox" name="video-save-privacy"> {{ checkbox|raw }}`)

Ich möchte auch mal anmerken, dass wir das Bundle hier öffentlich und kostenlos anbieten und uns niemand für den Support bezahlt. Ein wenig Eigeninitiative bei der Verwendung (bspw. einfach mal selber in die Symfony-Doku schauen) wäre schon schön. Habe heute auch nochmal ein paar Doku-Links ergänzt. Doch bitte nehmt das nicht alles so selbstverständlich...

**Comment by zonky2** [comment]
o.k. - als Contao-User ist man nicht gleichbedeutend Symfony-Entwickler...
für Contao 4.4 (Symfony 3): `app/Resources/HeimrichHannotVideoBundle/views/privacy`

**Comment by koertho** [comment]
Wie gesagt, ich wünsche mir einfach nur ein wenig mehr Eigeninitiative, dass heißt Dokumentation lesen und eventuell auch mal bei Google suchen, bevor man fragt. Aber lassen wir das jetzt ;)

Ich werde das raw mal ins Haupt-Template aufnehmen, da die Überschreibung aus irgend einem Grund nur in Bundles funktioniert, nicht im Projekt.

**Comment by koertho** [comment]
In Version 0.3.2 sollte es jetzt klappen
