### ISSUE TITLE
Module cannot be installed with a new PHP 8.0.2 and Contao 4.11.1 version

### ISSUE THREAD

**Issue by m-werk** [heimrichhannot/contao-video-bundle#8]
Hi, 
when I try to install the module, the following error message appears in the Contao-Manager:

Package heimrichhannot/contao-video-bundle has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

My PHP Version: 8.0.2
My Contao Version: 4.11.1

**Comment by koertho** [comment]
Hi, we're currently have no project with php 8, so we didn't updated any bundle for php 8. But I just made a short test and it looked good so I allowed it in version 0.10. Please provide feedback if it works or not :)

**Comment by koertho** [comment]
@m-werk I'm sorry, I forgot to tag the changes in request bundle. Now it should work.

**Comment by m-werk** [comment]
Hallo, ich schreibe jetzt mal auf deutsch, ist leicher für mich.

Folgendes: Ich hab es versucht zu installieren. Zuvor hatte ich alle Updates via CM gemacht. Alles prima. Dann hab ich versucht dieses Modul zu installieren und es kam wieder eine Fehlermeldung. Diesmal was anderes. 
So, nun bin ich hergegangen und hab meine PHP-Version mal auf die 7.4 gestellt. Dann hab ich wieder versucht das Modul zu installieren und wieder die gleiche Fehlermeldung. 

Hier die Fehlermeldung:
`
[7.0MiB/0.25s] Loading composer repositories with package information
[59.3MiB/1.84s] Updating dependencies
[1148.5MiB/9.44s] Your requirements could not be resolved to an installable set of packages.
[1148.5MiB/9.45s] 
  Problem 1
    - contao/manager-bundle is locked to version 4.11.1 and an update of this package was not requested.
    - Root composer.json requires heimrichhannot/contao-video-bundle ^0.10.0 -> satisfiable by heimrichhannot/contao-video-bundle[0.10.0].
    - Conclusion: don't install symfony/http-kernel v5.2.2 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.3 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.4 (conflict analysis result)
    - Conclusion: don't install symfony/http-kernel v5.2.5 (conflict analysis result)
    - contao/manager-bundle 4.11.1 requires symfony/web-profiler-bundle 4.4.* || 5.2.* -> satisfiable by symfony/web-profiler-bundle[v5.2.4].
    - heimrichhannot/contao-video-bundle 0.10.0 requires symfony/http-kernel ^3.4|^4.0 -> satisfiable by symfony/http-kernel[v3.4.0, ..., v3.4.47, v4.0.0, ..., v4.4.20].
    - You can only install one version of a package, so only one of these can be installed: symfony/http-kernel[v2.1.0, ..., v2.8.52, v3.0.0, ..., v3.4.47, v4.0.0, ..., v4.4.20, v5.0.0, ..., v5.2.5].
    - symfony/web-profiler-bundle v5.2.4 requires symfony/http-kernel ^5.2 -> satisfiable by symfony/http-kernel[v5.2.0, ..., v5.2.5].
    - Conclusion: don't install symfony/http-kernel v5.2.1 (conflict analysis result)
[1148.5MiB/9.45s] <warning>Running update with --no-dev does not mean require-dev is ignored, it just means the packages will not be installed. If dev requirements are blocking the update you have to resolve those problems.</warning>
[45.1MiB/10.36s] Memory usage: 45.08MB (peak: 1149.44MB), time: 10.37s.
[45.1MiB/10.37s] Finished Composer Cloud resolving.
`

**Comment by koertho** [comment]
Gleiches Problem wie in https://github.com/heimrichhannot/contao-email2username-bundle/issues/3, einfach auf Symfony 4 downgraden. Aktuell können wir nur 3 und 4 unterstützen.
